In [1]:
import pandas as pd

In [2]:
long_message_chain_df = pd.read_csv('result100\LongMessageChain.csv')
long_message_chain_df.head()

,subject,open,lineno,LMC,experience-based,statistics-based,tuning machine
0,keras-master,/Users/kaziknobo/Desktop/CSE 400 Thesis/Primar...,28,2,0,0,0
1,keras-master,/Users/kaziknobo/Desktop/CSE 400 Thesis/Primar...,45,2,0,0,0
2,keras-master,/Users/kaziknobo/Desktop/CSE 400 Thesis/Primar...,48,2,0,0,0
3,keras-master,/Users/kaziknobo/Desktop/CSE 400 Thesis/Primar...,62,2,0,0,0
4,keras-master,/Users/kaziknobo/Desktop/CSE 400 Thesis/Primar...,63,2,0,0,0

In [3]:
long_params_list_df = pd.read_csv('result100\LongParameterList.csv')
long_params_list_df.head()

,subject,open,lineno,PAR,experience-based,statistics-based,tuning machine
0,keras-master,/Users/kaziknobo/Desktop/CSE 400 Thesis/Primar...,20,1,0,0,0
1,keras-master,/Users/kaziknobo/Desktop/CSE 400 Thesis/Primar...,27,2,0,0,0
2,keras-master,/Users/kaziknobo/Desktop/CSE 400 Thesis/Primar...,35,2,0,0,0
3,keras-master,/Users/kaziknobo/Desktop/CSE 400 Thesis/Primar...,39,1,0,0,0
4,keras-master,/Users/kaziknobo/Desktop/CSE 400 Thesis/Primar...,52,1,0,0,0

In [11]:
long_lambda_func_df = pd.read_csv('result100\LongLambdaFunction.csv')
long_lambda_func_df.head()

,subject,open,lineno,NOC,PAR,NOO,experience-based,statistics-based,tuning machine
0,keras-master,/Users/kaziknobo/Desktop/CSE 400 Thesis/Primar...,121,52,0,5,0,0,0
1,keras-master,/Users/kaziknobo/Desktop/CSE 400 Thesis/Primar...,126,51,0,4,0,0,0
2,keras-master,/Users/kaziknobo/Desktop/CSE 400 Thesis/Primar...,94,36,1,5,0,0,0
3,keras-master,/Users/kaziknobo/Desktop/CSE 400 Thesis/Primar...,97,26,1,4,0,0,0
4,keras-master,/Users/kaziknobo/Desktop/CSE 400 Thesis/Primar...,37,47,1,6,0,0,0

In [4]:
def create_dataset_for_merging(df):
    smells = df['tuning machine'] == 1
    no_smells = df['tuning machine'] == 0

    df_smells = df[smells]
    df_no_smells = df[no_smells]
    random_df_no_smells = df_no_smells.sample(n=len(df_smells))

    final_df = pd.concat([df_smells, random_df_no_smells], ignore_index=True)
    final_df = final_df.sample(frac=1).reset_index(drop=True)
    final_df.drop(columns=['experience-based', 'statistics-based'], inplace=True)
    # final_df.head()
    return final_df

In [12]:
LMC_df = create_dataset_for_merging(long_message_chain_df)
LPL_df = create_dataset_for_merging(long_params_list_df)
LLF_df = create_dataset_for_merging(long_lambda_func_df)

In [6]:
LMC_df.info()
LMC_df.head(100)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9148 entries, 0 to 9147
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   subject         9148 non-null   object
 1   open            9148 non-null   object
 2   lineno          9148 non-null   int64
 3   LMC             9148 non-null   int64
 4   tuning machine  9148 non-null   int64
dtypes: int64(3), object(2)
memory usage: 357.5+ KB

,subject,open,lineno,LMC,tuning machine
0,django-main,/Users/kaziknobo/Desktop/CSE 400 Thesis/Primar...,213,2,0
1,sentry-master,/Users/kaziknobo/Desktop/CSE 400 Thesis/Primar...,345,2,0
2,stable-diffusion-webui-master,/Users/kaziknobo/Desktop/CSE 400 Thesis/Primar...,41,2,0
3,neural-amp-modeler-main,/Users/kaziknobo/Desktop/CSE 400 Thesis/Primar...,969,4,1
4,stable-diffusion-webui-master,/Users/kaziknobo/Desktop/CSE 400 Thesis/Primar...,105,5,1
...,...,...,...,...,...
95,neural-amp-modeler-main,/Users/kaziknobo/Desktop/CSE 400 Thesis/Primar...,957,3,0
96,neural-amp-modeler-main,/Users/kaziknobo/Desktop/CSE 400 Thesis/Primar...,304,3,0
97,neural-amp-modeler-main,/Users/kaziknobo/Desktop/CSE 400 Thesis/Primar...,606,2,0
98,core-dev,/Users/kaziknobo/Desktop/CSE 400 Thesis/Primar...,142,2,0
99,sentry-master,/Users/kaziknobo/Desktop/CSE 400 Thesis/Primar...,1268,4,1

In [7]:
LPL_df.info()
LPL_df.head(100)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13418 entries, 0 to 13417
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   subject         13418 non-null  object
 1   open            13418 non-null  object
 2   lineno          13418 non-null  int64
 3   PAR             13418 non-null  int64
 4   tuning machine  13418 non-null  int64
dtypes: int64(3), object(2)
memory usage: 524.3+ KB

,subject,open,lineno,PAR,tuning machine
0,neural-amp-modeler-main,/Users/kaziknobo/Desktop/CSE 400 Thesis/Primar...,753,5,1
1,django-main,/Users/kaziknobo/Desktop/CSE 400 Thesis/Primar...,777,1,0
2,neural-amp-modeler-main,/Users/kaziknobo/Desktop/CSE 400 Thesis/Primar...,50,1,0
3,django-main,/Users/kaziknobo/Desktop/CSE 400 Thesis/Primar...,408,5,1
4,sentry-master,/Users/kaziknobo/Desktop/CSE 400 Thesis/Primar...,32,1,0
...,...,...,...,...,...
95,sentry-master,/Users/kaziknobo/Desktop/CSE 400 Thesis/Primar...,362,5,1
96,neural-amp-modeler-main,/Users/kaziknobo/Desktop/CSE 400 Thesis/Primar...,1014,6,1
97,sentry-master,/Users/kaziknobo/Desktop/CSE 400 Thesis/Primar...,61,2,0
98,fastapi-master,/Users/kaziknobo/Desktop/CSE 400 Thesis/Primar...,1056,14,1
99,sentry-master,/Users/kaziknobo/Desktop/CSE 400 Thesis/Primar...,154,2,0

In [13]:
LLF_df.info()
LLF_df.head(100)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 776 entries, 0 to 775
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   subject         776 non-null    object
 1   open            776 non-null    object
 2   lineno          776 non-null    int64
 3   NOC             776 non-null    int64
 4   PAR             776 non-null    int64
 5   NOO             776 non-null    int64
 6   tuning machine  776 non-null    int64
dtypes: int64(5), object(2)
memory usage: 42.6+ KB

,subject,open,lineno,NOC,PAR,NOO,tuning machine
0,sentry-master,/Users/kaziknobo/Desktop/CSE 400 Thesis/Primar...,149,55,1,6,0
1,flask-main,/Users/kaziknobo/Desktop/CSE 400 Thesis/Primar...,257,42,0,5,0
2,core-dev,/Users/kaziknobo/Desktop/CSE 400 Thesis/Primar...,160,124,1,31,1
3,sqlglot-main,/Users/kaziknobo/Desktop/CSE 400 Thesis/Primar...,421,84,2,15,1
4,sqlglot-main,/Users/kaziknobo/Desktop/CSE 400 Thesis/Primar...,562,28,1,3,0
...,...,...,...,...,...,...,...
95,sentry-master,/Users/kaziknobo/Desktop/CSE 400 Thesis/Primar...,186,205,2,36,1
96,sqlglot-main,/Users/kaziknobo/Desktop/CSE 400 Thesis/Primar...,97,98,1,15,1
97,sentry-master,/Users/kaziknobo/Desktop/CSE 400 Thesis/Primar...,717,87,1,8,0
98,sqlglot-main,/Users/kaziknobo/Desktop/CSE 400 Thesis/Primar...,385,86,0,18,1
99,sqlglot-main,/Users/kaziknobo/Desktop/CSE 400 Thesis/Primar...,640,127,2,15,1

In [15]:
column_mapping_LMC = {'subject':'Project', 'open':'File Name','lineno':'Line_LMC', 'LMC':'LMC', 'tuning machine':'LMCS'}
column_mapping_LPL = {'subject':'Project', 'open':'File Name','lineno':'Line_LPL', 'PAR':'LPLPAR', 'tuning machine':'LPL'}
column_mapping_LLF = {'subject':'Project', 'open':'File Name','lineno':'Line_LLF', 'PAR':'LLFPAR', 'tuning machine':'LLF'}

LMC_df.rename(columns=column_mapping_LMC, inplace=True)
LPL_df.rename(columns=column_mapping_LPL, inplace=True)
LLF_df.rename(columns=column_mapping_LLF, inplace=True)

In [18]:
LMC_LPL = pd.merge(LMC_df, LPL_df, on=['Project', 'File Name'], how='outer')
main_df = pd.merge(LMC_LPL, LLF_df, on=['Project', 'File Name'], how='outer')
main_df.fillna(0, inplace=True)
main_df.info()
main_df.head(1000)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38523 entries, 0 to 38522
Data columns (total 13 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Project    38523 non-null  object
 1   File Name  38523 non-null  object
 2   Line_LMC   38523 non-null  float64
 3   LMC        38523 non-null  float64
 4   LMCS       38523 non-null  float64
 5   Line_LPL   38523 non-null  float64
 6   LPLPAR     38523 non-null  float64
 7   LPL        38523 non-null  float64
 8   Line_LLF   38523 non-null  float64
 9   NOC        38523 non-null  float64
 10  LLFPAR     38523 non-null  float64
 11  NOO        38523 non-null  float64
 12  LLF        38523 non-null  float64
dtypes: float64(11), object(2)
memory usage: 3.8+ MB

,Project,File Name,Line_LMC,LMC,LMCS,Line_LPL,LPLPAR,LPL,Line_LLF,NOC,LLFPAR,NOO,LLF
0,neural-amp-modeler-main,/Users/kaziknobo/Desktop/CSE 400 Thesis/Primar...,841.0,4.0,1.0,1660.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
1,neural-amp-modeler-main,/Users/kaziknobo/Desktop/CSE 400 Thesis/Primar...,841.0,4.0,1.0,1405.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0
2,neural-amp-modeler-main,/Users/kaziknobo/Desktop/CSE 400 Thesis/Primar...,841.0,4.0,1.0,1617.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
3,neural-amp-modeler-main,/Users/kaziknobo/Desktop/CSE 400 Thesis/Primar...,841.0,4.0,1.0,1912.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0
4,neural-amp-modeler-main,/Users/kaziknobo/Desktop/CSE 400 Thesis/Primar...,841.0,4.0,1.0,2051.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,sentry-master,/Users/kaziknobo/Desktop/CSE 400 Thesis/Primar...,7311.0,5.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
996,sentry-master,/Users/kaziknobo/Desktop/CSE 400 Thesis/Primar...,3129.0,4.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
997,sentry-master,/Users/kaziknobo/Desktop/CSE 400 Thesis/Primar...,5757.0,4.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
998,sentry-master,/Users/kaziknobo/Desktop/CSE 400 Thesis/Primar...,6331.0,4.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
999,sentry-master,/Users/kaziknobo/Desktop/CSE 400 Thesis/Primar...,873.0,5.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [19]:
main_df.to_csv('LMC_LPL_LLF.csv', index=False)